#### Ch. 07

In [1]:
import numpy as np


In [4]:
numbers= np.array([2,3,5,7,11])

In [5]:
type(numbers)

numpy.ndarray

In [6]:
numbers

array([ 2,  3,  5,  7, 11])

In [7]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [1]:
import numpy as np

integers = np.array([[1,2,3],[4,5,6]])
print(integers)

floats = np.array([0.0,0.1,0.2,0.3,0.4])
print(floats)

[[1 2 3]
 [4 5 6]]
[0.  0.1 0.2 0.3 0.4]


In [3]:
integers.dtype


dtype('float64')

In [4]:
floats.dtype

dtype('float64')